{
 "title": "Logging",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "[WARN] - hyperbytedb-0",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{instance=\"hyperbytedb/hyperbytedb-0:hyperbytedb\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "[WARN] - hyperbytedb-1",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{instance=\"hyperbytedb/hyperbytedb-1:hyperbytedb\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "[ERROR] - hyperbytedb-0",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{instance=\"hyperbytedb/hyperbytedb-0:hyperbytedb\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "[ERROR] - hyperbytedb-1",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{instance=\"hyperbytedb/hyperbytedb-1:hyperbytedb\"} |= `ERROR`"
    }
   ]
  }
 ]
}