global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "hyperbytedb"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["hyperbytedb:8086"]
        labels:
          instance: "hyperbytedb"
