{
 "title": "Machine Monitoring",
 "tags": [ "DevOps" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"host\""
    }
   },
   { "name": "ds", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Quick View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE \"host\" =~ /^$server$/ AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "CPU/Memory info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_guest\") AS \"Usage Guest\", mean(\"usage_guest_nice\") AS \"Usage Guest Nice\", mean(\"usage_idle\") AS \"Usage Idle\", mean(\"usage_iowait\") AS \"Usage IO Wait\", mean(\"usage_irq\") AS \"Usage IRQ\", mean(\"usage_nice\") AS \"Usage Nice\", mean(\"usage_softirq\") AS \"Usage Soft IRQ\", mean(\"usage_steal\") AS \"Usage Steal\", mean(\"usage_system\") AS \"Usage System\", mean(\"usage_user\") AS \"Usage User\" FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage Guest" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_guest_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage Guest Nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage IO Wait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage IRQ" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage Nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage Soft IRQ" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage Steal" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage System" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usage User" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Load Averages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load (short)" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load (medium)" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load (long)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Buffered" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Cached" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "inactive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Inactive" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes Info",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Running" ], "type": "alias" }
      ],
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Zombies" ], "type": "alias" }
      ],
      [
       { "params": [ "stopped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Stopped" ], "type": "alias" }
      ],
      [
       { "params": [ "paging" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Paging" ], "type": "alias" }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Sleeping" ], "type": "alias" }
      ],
      [
       { "params": [ "unknown" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Unknown" ], "type": "alias" }
      ],
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Blocked" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes Stat Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "CPU Usage: $tag_process_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "pidfile" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": " SELECT mean(\"cpu_usage\") FROM \"procstat\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY \"process_name\",time($interval),host fill(null)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes Stat Info Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Memory VMS: $tag_process_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "pidfile" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": " SELECT mean(\"memory_vms\") FROM \"procstat\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY \"process_name\",time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Memory RSS: $tag_process_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "pidfile" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": " SELECT mean(\"memory_rss\") FROM \"procstat\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY \"process_name\",time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Memory SWAP: $tag_process_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "pidfile" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": " SELECT mean(\"memory_swap\") FROM \"procstat\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY \"process_name\",time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes Stat Info Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Write Count: $tag_process_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "pidfile" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": " SELECT mean(\"write_count\") FROM \"procstat\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY \"process_name\",time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Write Bytes: $tag_process_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "pidfile" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": " SELECT mean(\"write_bytes\") FROM \"procstat\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY \"process_name\",time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Read Bytes: $tag_process_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "pidfile" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": " SELECT mean(\"read_bytes\") FROM \"procstat\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY \"process_name\",time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "Read Count: $tag_process_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "pidfile" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": " SELECT mean(\"read_count\") FROM \"procstat\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY \"process_name\",time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Disk I/O Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_host - $tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"reads\"), 1s) AS \"Reads\", non_negative_derivative(mean(\"writes\"), 1s) AS \"Writes\" FROM \"diskio\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"host\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_host - $tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(last(\"weighted_io_time\"), 1ms) as \"iops_in_progress\" from \"diskio\" WHERE   (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"host\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "alias": "$tag_host- $tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"Reads\", non_negative_derivative(mean(\"write_bytes\"), 1s) AS \"Writes\" FROM \"diskio\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), \"host\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Reads" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "alias": "$tag_host - $tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "Read Time" ], "type": "alias" }
      ],
      [
       { "params": [ "write_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "Write Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col ($tag_path)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk inodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"inodes_free\") AS \"inodes free\", mean(\"inodes_used\") AS \"inotes used\" FROM \"disk\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time(10s), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "inodes_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "inodes free" ], "type": "alias" }
      ],
      [
       { "params": [ "inodes_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "inotes used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col - $tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT derivative(mean(\"io_time\"), 1ms) AS \"IO utilisation\" FROM \"diskio\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($__interval), \"name\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "read_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Read Time" ], "type": "alias" }
      ],
      [
       { "params": [ "write_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Write Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Swap I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "SELECT non_negative_derivative(mean(\"in\"), 10s) AS \"in\", non_negative_derivative(mean(\"out\"), 10s) AS \"out\" FROM \"swap\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 78 },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Network In/Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$col ($tag_interface)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(first(bytes_recv), 1s) * 8 as \"in bits/sec\", derivative(first(bytes_sent), 1s) * 8 as \"out bits/sec\" FROM net WHERE host =~ /^$server$/ AND interface =~ /(vlan|eth|bond|vmbr|ens|eno|ixl|gb|enp).*/ AND interface !~ /veth/ AND $timeFilter GROUP BY time($__interval), \"host\", \"interface\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Packets In/Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col ($tag_interface)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT NON_NEGATIVE_DIFFERENCE(mean(\"packets_recv\"))/10 AS \"in\", NON_NEGATIVE_DIFFERENCE(mean(\"packets_sent\"))/10 AS \"out\" FROM net WHERE host =~ /^$server$/ AND interface =~ /(vlan|eth|bond|vmbr|ens|eno|ix|gb|enp).*/ AND interface !~ /veth/ AND $timeFilter GROUP BY time($__interval), \"host\", \"interface\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netstat",
     "select": [
      [
       { "params": [ "tcp_close" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CLOSED" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_close_wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CLOSE_WAIT" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_closing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CLOSING" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ESTABLISHED" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_fin_wait1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "FIN_WAIT1" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_fin_wait2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "FIN_WAIT2" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_last_ack" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "LAST_ACK" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_syn_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "SYN_RECV" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_syn_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "SYN_SENT" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_time_wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "TIME_WAIT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "UDP Sockets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netstat",
     "query": "SELECT mean(\"tcp_close\") AS \"CLOSED\", mean(\"tcp_close_wait\") AS \"CLOSE_WAIT\", mean(\"tcp_closing\") AS \"CLOSING\", mean(\"tcp_established\") AS \"ESTABLISHED\", mean(\"tcp_fin_wait1\") AS \"FIN_WAIT1\", mean(\"tcp_fin_wait2\") AS \"FIN_WAIT2\", mean(\"tcp_last_ack\") AS \"LAST_ACK\", mean(\"tcp_syn_recv\") AS \"SYN_RECV\", mean(\"tcp_syn_sent\") AS \"SYN_SENT\", mean(\"tcp_time_wait\") AS \"TIME_WAIT\" FROM \"netstat\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "udp_socket" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "alias": "$tag_host: $col ($tag_interface)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") AS \"Errors In\", mean(\"err_out\") AS \"Errors Out\" FROM net WHERE host =~ /^$server$/ AND interface =~ /(vlan|eth|bond|vmbr|ens|eno|ix|gb).*/ AND interface !~ /veth/ AND $timeFilter GROUP BY time($interval), \"host\", \"interface\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "alias": "$tag_host: $col ($tag_interface)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") AS \"Drops In\", mean(\"drop_out\") AS \"Drops Out\" FROM net WHERE host =~ /^$server$/ AND interface =~ /(vlan|eth|bond|vmbr|ens|eno|ix|gb).*/ AND interface !~ /veth/ AND $timeFilter GROUP BY time($interval), \"host\", \"interface\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  }
 ]
}